# Generated by Django 5.2.11 on 2026-02-04 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_book_category_book_is_featured_book_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary identifier for the order', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Purchase amount in GBP', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current order status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Order creation timestamp')),
                ('book', models.ForeignKey(help_text='Book that was purchased', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='books.book')),
                ('buyer', models.ForeignKey(help_text='User who purchased the book', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('buyer', 'book'), name='unique_purchase_per_buyer_book')],
            },
        ),
    ]
