# Generated by Django 5.2.11 on 2026-04-23 18:06

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def set_expiry_for_existing_orders(apps, schema_editor):
    """Set expires_at to 6 months from now for all existing completed orders."""
    Order = apps.get_model('orders', 'Order')
    expiry_date = timezone.now() + timedelta(days=180)
    Order.objects.filter(
        status='COMPLETED',
        expires_at__isnull=True
    ).update(expires_at=expiry_date)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Access expiry timestamp (6 months from purchase)', null=True),
        ),
        migrations.RunPython(set_expiry_for_existing_orders, migrations.RunPython.noop),
    ]
