# Generated by Django 5.2.11 on 2026-04-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_upload_books',
            field=models.BooleanField(default=False, help_text='Designates whether this user can upload books.'),
        ),
    ]
