# Generated by Django 5.2.11 on 2026-04-24 19:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_can_upload_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
