"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
import ssl
import dj_database_url
import environ

# Initialize django-environ
env = environ.Env()
# Read .env file if it exists (for local development)
environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-*nfz1(-5$%h3%s=+9$43pl3(^(t&^ko(g+!h=ep_%(x0k3i)b4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])


# S3-compatible object storage settings (AWS S3, Cloudflare R2, etc.)
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default=None)
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default=None)
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='enquad-book-files')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='auto')
AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL', default=None)
AWS_S3_SIGNATURE_VERSION = env('AWS_S3_SIGNATURE_VERSION', default='s3v4')
AWS_S3_ADDRESSING_STYLE = env('AWS_S3_ADDRESSING_STYLE', default='path')
AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN', default=None)
AWS_S3_FILE_OVERWRITE = False
# Note: ACLs are disabled on the bucket, using bucket policy for public access instead
AWS_DEFAULT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_QUERYSTRING_AUTH = env.bool('AWS_QUERYSTRING_AUTH', default=False)

# Backward-compatible AWS fallback only when no custom endpoint is used.
if not AWS_S3_CUSTOM_DOMAIN and not AWS_S3_ENDPOINT_URL and AWS_STORAGE_BUCKET_NAME:
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'apps.users',
    'apps.auth',
    'apps.books',
    'apps.library',
    'apps.wallet',
    'apps.orders',
    'apps.social',
]

# Add django-storages only when using S3
if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    INSTALLED_APPS.append('storages')

# Django 4.2+ uses STORAGES dict
# Use S3 if credentials are provided, otherwise use local filesystem
if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    # Production: Use S3 for media, Whitenoise for static
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Local development: Use filesystem
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'bookers'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', '221031'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

database_url = os.getenv('DATABASE_URL')
if database_url:
    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600)
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
SITE_BASE_URL = env('SITE_BASE_URL', default='https://quaduni.com')
KEEPZ_ECOMMERCE_BASE_URL = env(
    'KEEPZ_ECOMMERCE_BASE_URL',
    default='https://gateway.dev.keepz.me/ecommerce-service',
)
KEEPZ_IDENTIFIER = env('KEEPZ_IDENTIFIER', default='')
KEEPZ_INTEGRATOR_ID = env('KEEPZ_INTEGRATOR_ID', default='')
KEEPZ_RECEIVER_ID = env('KEEPZ_RECEIVER_ID', default='')
KEEPZ_RECEIVER_TYPE = env('KEEPZ_RECEIVER_TYPE', default='BRANCH')
KEEPZ_PROVIDER_PUBLIC_KEY = env('KEEPZ_PROVIDER_PUBLIC_KEY', default='')
KEEPZ_INTEGRATOR_PRIVATE_KEY = env('KEEPZ_INTEGRATOR_PRIVATE_KEY', default='')
KEEPZ_INTEGRATOR_PUBLIC_KEY = env('KEEPZ_INTEGRATOR_PUBLIC_KEY', default='')
KEEPZ_RSA_PADDING = env('KEEPZ_RSA_PADDING', default='OAEP')
KEEPZ_DEFAULT_CURRENCY = env('KEEPZ_DEFAULT_CURRENCY', default='GEL')

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Private media storage for secure files (page images)
# These files are NOT served via MEDIA_URL and require authentication
PRIVATE_MEDIA_ROOT = BASE_DIR / 'private_media'

# Default storage backend is configured in STORAGES dict above
# Uses S3 when AWS credentials are provided, filesystem otherwise

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.auth.authentication.CookieJWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
}

# SimpleJWT settings (refresh token support)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')

AUTH_COOKIE_DOMAIN = env('AUTH_COOKIE_DOMAIN', default=None)
AUTH_COOKIE_SECURE = env.bool('AUTH_COOKIE_SECURE', default=not DEBUG)
AUTH_COOKIE_SAMESITE = env('AUTH_COOKIE_SAMESITE', default='None' if not DEBUG else 'Lax')
AUTH_ACCESS_COOKIE_NAME = env('AUTH_ACCESS_COOKIE_NAME', default='bookers_access')
AUTH_REFRESH_COOKIE_NAME = env('AUTH_REFRESH_COOKIE_NAME', default='bookers_refresh')
AUTH_ACCESS_COOKIE_PATH = env('AUTH_ACCESS_COOKIE_PATH', default='/')
AUTH_REFRESH_COOKIE_PATH = env('AUTH_REFRESH_COOKIE_PATH', default='/auth')
AUTH_ACCESS_COOKIE_MAX_AGE = int(SIMPLE_JWT['ACCESS_TOKEN_LIFETIME'].total_seconds())
AUTH_REFRESH_COOKIE_MAX_AGE = int(SIMPLE_JWT['REFRESH_TOKEN_LIFETIME'].total_seconds())

# CORS
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    "http://quaduni.com",
])
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=CORS_ALLOWED_ORIGINS)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SAMESITE = env('CSRF_COOKIE_SAMESITE', default='None' if not DEBUG else 'Lax')
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

AUTH_USER_MODEL = 'users.User'

# Celery
REDIS_URL = env('REDIS_URL', default=None)

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', '1800'))

if REDIS_URL and REDIS_URL.startswith('rediss://'):
    CELERY_BROKER_USE_SSL = {
        'ssl_cert_reqs': ssl.CERT_NONE
    }
    CELERY_REDIS_BACKEND_USE_SSL = {
        'ssl_cert_reqs': ssl.CERT_NONE
    }

CELERY_REDIS_RETRY_ON_TIMEOUT = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CACHE_DEFAULT_TIMEOUT = env.int('CACHE_DEFAULT_TIMEOUT', default=300)
if REDIS_URL:
    redis_cache_options = {
        'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        'IGNORE_EXCEPTIONS': True,
    }
    if REDIS_URL.startswith('rediss://'):
        redis_cache_options['CONNECTION_POOL_KWARGS'] = {
            'ssl_cert_reqs': ssl.CERT_NONE,
        }

    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
            'KEY_PREFIX': 'bookers',
            'OPTIONS': redis_cache_options,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'bookers-local-cache',
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
        }
    }

# Books app settings
BOOKS_MAX_COVER_SIZE = 5 * 1024 * 1024  # 5MB
BOOKS_ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/gif', 'image/webp']

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

AUTH_USER_MODEL = 'users.User'
