# Generated by Django 5.2.11 on 2026-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.PositiveIntegerField(default=0, help_text='Total number of pages (set after file conversion)'),
        ),
    ]
