# Generated by Django 5.2.11 on 2026-02-05 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_pagenote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='intake_attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='intake_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='intake_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='intake_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='intake_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', help_text='Canonical draft intake processing state.', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='intake_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['owner', 'status', 'intake_status'], name='books_owner_status_intake_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status', 'intake_status', 'intake_updated_at'], name='books_status_intake_upd_idx'),
        ),
    ]
