# Generated by Django 5.2.11 on 2026-02-05 23:00

import apps.books.storage
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_intake_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=apps.books.storage.PrivateMediaStorage(), upload_to='draft_elements/images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_image_assets', to='books.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=16)),
                ('page_number', models.PositiveIntegerField()),
                ('x', models.DecimalField(decimal_places=4, max_digits=6)),
                ('y', models.DecimalField(decimal_places=4, max_digits=6)),
                ('width', models.DecimalField(decimal_places=4, max_digits=6)),
                ('height', models.DecimalField(decimal_places=4, max_digits=6)),
                ('z_index', models.IntegerField(default=0)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_elements', to='books.book')),
                ('image_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='books.draftimageasset')),
            ],
            options={
                'ordering': ['page_number', 'z_index', 'id'],
                'indexes': [models.Index(fields=['book', 'page_number', 'z_index'], name='draft_el_book_page_z_idx'), models.Index(fields=['book', 'element_type'], name='draft_el_book_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('x__gte', 0), ('x__lte', 1)), name='draft_el_x_0_1'), models.CheckConstraint(condition=models.Q(('y__gte', 0), ('y__lte', 1)), name='draft_el_y_0_1'), models.CheckConstraint(condition=models.Q(('width__gt', 0), ('width__lte', 1)), name='draft_el_w_gt0_1'), models.CheckConstraint(condition=models.Q(('height__gt', 0), ('height__lte', 1)), name='draft_el_h_gt0_1'), models.CheckConstraint(condition=models.Q(('x__lte', django.db.models.expressions.CombinedExpression(models.Value(1), '-', models.F('width')))), name='draft_el_x_plus_w_lte_1'), models.CheckConstraint(condition=models.Q(('y__lte', django.db.models.expressions.CombinedExpression(models.Value(1), '-', models.F('height')))), name='draft_el_y_plus_h_lte_1'), models.CheckConstraint(condition=models.Q(models.Q(('element_type', 'text'), ('text_content__isnull', False), ('image_asset__isnull', True)), models.Q(('element_type', 'image'), ('text_content__isnull', True), ('image_asset__isnull', False)), _connector='OR'), name='draft_el_payload_by_type'), models.CheckConstraint(condition=models.Q(('page_number__gte', 1)), name='draft_el_page_gte_1')],
            },
        ),
    ]
