# Generated by Django 5.2.11 on 2026-02-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_draft_editor_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='text_content',
            field=models.TextField(blank=True, default='', help_text='Extracted text content from PDF for editing'),
        ),
    ]
