# Generated by Django 5.2.11 on 2026-02-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_add_page_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='text_content',
        ),
        migrations.AddField(
            model_name='bookpage',
            name='content',
            field=models.TextField(blank=True, default='', help_text='HTML content for page editing'),
        ),
    ]
