# Generated by Django 5.2.11 on 2026-02-06 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_add_page_version_and_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('edit', 'Edit'), ('publish', 'Publish')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Action-specific details: page_number/version for edits, attempt for uploads, page_count for publish')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['book', 'timestamp'], name='audit_book_time_idx'), models.Index(fields=['user', 'timestamp'], name='audit_user_time_idx'), models.Index(fields=['action', 'timestamp'], name='audit_action_time_idx')],
            },
        ),
    ]
