# Generated by Django 5.2.11 on 2026-02-16 20:36

import apps.books.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_book_publish_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(help_text='Page number where image appears (1-based)')),
                ('xref', models.PositiveIntegerField(help_text='PDF xref identifier for the image')),
                ('image', models.ImageField(help_text='Extracted image file', storage=apps.books.storage.PrivateMediaStorage(), upload_to='extracted_images/%Y/%m/%d/')),
                ('original_ext', models.CharField(help_text='Original image format (png, jpeg, etc.)', max_length=10)),
                ('width', models.PositiveIntegerField(help_text='Image width in pixels')),
                ('height', models.PositiveIntegerField(help_text='Image height in pixels')),
                ('bbox_x0', models.FloatField(blank=True, help_text='Position on page: left coordinate', null=True)),
                ('bbox_y0', models.FloatField(blank=True, help_text='Position on page: top coordinate', null=True)),
                ('bbox_x1', models.FloatField(blank=True, help_text='Position on page: right coordinate', null=True)),
                ('bbox_y1', models.FloatField(blank=True, help_text='Position on page: bottom coordinate', null=True)),
                ('has_transparency', models.BooleanField(default=False, help_text='Whether image had mask/transparency applied')),
                ('colorspace', models.PositiveIntegerField(default=0, help_text='PDF colorspace identifier')),
                ('file_size', models.PositiveIntegerField(help_text='Image file size in bytes')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Extracted Image',
                'verbose_name_plural': 'Extracted Images',
                'ordering': ['page_number', 'xref'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='extraction_diagnostics',
            field=models.JSONField(blank=True, default=list, help_text='Text extraction warnings and diagnostics'),
        ),
        migrations.AddField(
            model_name='book',
            name='extraction_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='extraction_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='extraction_pages_processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='extraction_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', help_text='Text extraction status for new reader experience', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='extraction_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['extraction_status', 'extraction_updated_at'], name='books_ext_status_upd_idx'),
        ),
        migrations.AddField(
            model_name='extractedimage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_images', to='books.book'),
        ),
        migrations.AddIndex(
            model_name='extractedimage',
            index=models.Index(fields=['book', 'page_number'], name='extimg_book_page_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractedimage',
            constraint=models.UniqueConstraint(fields=('book', 'page_number', 'xref'), name='unique_image_per_page_xref'),
        ),
    ]
