# Generated by Django 5.2.11 on 2026-02-16 21:20

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_extractedimage_book_extraction_diagnostics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('blocks', models.JSONField(default=list, help_text='List of content blocks with type, content, and metadata')),
                ('version', models.PositiveIntegerField(default=1)),
                ('block_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pages', to='books.book')),
            ],
            options={
                'ordering': ['page_number'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['blocks'], name='book_content_blocks_gin'), models.Index(fields=['book', 'page_number'], name='books_bookc_book_id_5c28b1_idx'), models.Index(fields=['book', 'updated_at'], name='books_bookc_book_id_9ebda5_idx')],
                'constraints': [models.UniqueConstraint(fields=('book', 'page_number'), name='unique_book_page_content')],
            },
        ),
    ]
