# Generated by Django 5.2.11 on 2026-02-16 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_bookcontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version number (1, 2, 3...)')),
                ('blocks_snapshot', models.JSONField(default=list, help_text='Complete copy of blocks at this version')),
                ('version_type', models.CharField(choices=[('auto', 'Auto-saved'), ('manual', 'Manual save'), ('publish', 'Published'), ('revert', 'Reverted')], default='manual', help_text='Type of version: auto-save, manual save, publish, or revert', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this version was created')),
                ('change_summary', models.TextField(blank=True, help_text='Human-readable summary of changes')),
                ('blocks_changed', models.JSONField(default=list, help_text='List of block IDs that changed from previous version')),
                ('book_content', models.ForeignKey(help_text='The content page this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='books.bookcontent')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Version',
                'verbose_name_plural': 'Content Versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['book_content', 'version_number'], name='content_version_lookup_idx'), models.Index(fields=['created_at'], name='content_version_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('book_content', 'version_number'), name='unique_content_version_number')],
            },
        ),
    ]
