# Generated by Django 5.x on 2026-02-16 22:00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add theme_data JSONField to Book model for per-book theming."""

    dependencies = [
        ('books', '0021_content_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='theme_data',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Theme configuration for book display (paper_background, font_family)',
            ),
        ),
    ]
