# Generated by Django 5.2.11 on 2026-02-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_add_theme_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_index', models.PositiveIntegerField(default=0, help_text='Current reading position as 0-based block index')),
                ('last_read_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last progress update')),
                ('book', models.ForeignKey(help_text='Book being read', on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='books.book')),
                ('user', models.ForeignKey(help_text='User whose progress is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Progress',
                'verbose_name_plural': 'Reading Progress',
                'ordering': ['-last_read_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
