# Generated by Django 5.2.11 on 2026-02-17 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_reading_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookPage',
        ),
    ]
