# Generated by Django 5.2.11 on 2026-02-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_add_chapter_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingProgress',
        ),
    ]
