# Generated by Django 5.2.11 on 2026-04-17 11:29

import apps.books.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfile',
            name='file',
            field=models.FileField(storage=apps.books.storage.PrivateMediaStorage(), upload_to='books/files/%Y/%m/'),
        ),
    ]
