# Generated by Django 5.2.11 on 2026-04-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_alter_bookfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reader_render_preference',
            field=models.CharField(choices=[('text', 'Text'), ('exact_visual', 'Exact Visual')], default='text', help_text='Preferred reader rendering mode for uploaded PDFs', max_length=20),
        ),
    ]
