# Generated by Django 5.2.11 on 2026-05-01 09:00

import apps.books.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_book_reader_render_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='access_type',
            field=models.CharField(choices=[('educational', 'სასწავლო'), ('scientific', 'სამეცნიერო')], default='educational', help_text='Book access and download policy', max_length=20),
        ),
        migrations.AddField(
            model_name='bookfile',
            name='preview_file',
            field=models.FileField(blank=True, null=True, storage=apps.books.storage.PrivateMediaStorage(), upload_to='books/previews/%Y/%m/'),
        ),
    ]
