# Generated by Django 5.2.11 on 2026-05-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_remove_bookcontent_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish_error',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_finished_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_started_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_status',
        ),
    ]
