# Generated by Django 5.2.11 on 2026-05-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_remove_book_publish_error_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_owner_status_intake_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_status_intake_upd_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='intake_attempt',
        ),
        migrations.RemoveField(
            model_name='book',
            name='intake_diagnostics',
        ),
        migrations.RemoveField(
            model_name='book',
            name='intake_error',
        ),
        migrations.RemoveField(
            model_name='book',
            name='intake_finished_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='intake_started_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='intake_status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='intake_updated_at',
        ),
    ]
