# Generated by Django 5.2.11 on 2026-05-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_remove_book_books_owner_status_intake_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAuditLog',
        ),
    ]
