# Generated by Django 5.2.11 on 2026-05-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_delete_bookauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs/%Y/%m/'),
        ),
    ]
