# Generated by Django 5.2.11 on 2026-05-02 11:37

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_book_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=apps.books.models.select_private_storage, upload_to='books/pdfs/%Y/%m/'),
        ),
    ]
