# Generated by Django 5.2.11 on 2026-02-28 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_communitypostcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.communitypostcomment'),
        ),
    ]
