# Generated by Django 5.2.11 on 2026-03-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_communitypostlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='comments',
        ),
    ]
